### ISSUE TITLE
Try out AssemblyScript 

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-client-js#12]
https://github.com/AssemblyScript/assemblyscript/blob/master/README.md

**Comment by johan-bjareholt** [comment]
Sounds worthless IMO, we have no use for extra performance in aw-client-js.
If we actually did something computationally expensive in aw-client-js we're doing something wrong.
As you can see even in their README, all examples are of programs which are heavy.

**Comment by ErikBjare** [comment]
I know, I just want to try it out.

**Comment by johan-bjareholt** [comment]
Well, let's not do it on this project then, would just be unnecessary build dependencies.

**Comment by ErikBjare** [comment]
I wasn't going to mere anything, just the only TypeScript project I have that's not years old.

**Comment by johan-bjareholt** [comment]
But in that case, why create an issue? Seems more like a personal ToDo rather than a issue.

**Comment by ErikBjare** [comment]
Fair, will probably never get around to it anyway.
